apiVersion: v1
kind: Service
metadata:
  name: {{ include "ploverdb.fullname" . }}
  namespace: rtx
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ploverdb
