apiVersion: v1
kind: Service
metadata:
  name: {{ include "PloverDB.fullname" . }}
  namespace: rtx
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "PloverDB.selectorLabels" . | nindent 4 }}
